title: Packrinth
description: CLI tool for creating and maintaining your own Minecraft modpack
theme: just-the-docs
color_scheme: dark

url: https://packrinth.thijzert.nl

aux_links:
  crates.io: https://crates.io/crates/packrinth
  Lib Documentation: https://docs.rs/packrinth
  GitHub Repository: https://github.com/Thijzert123/packrinth

callouts:
  important:
    title: Important
    color: yellow
  summary:
    title: Summary
    color: purple
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

ga_tracking: G-8FM4VPDZ2T
