name: Cargo

on:
  push:
    branches: [ "main" ]
    paths: [ "src/**", "Cargo.toml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "src/**", "Cargo.toml" ]

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  cargo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cargo
      run: cargo build --verbose && cargo test --verbose && cargo clippy --verbose
